=== yavdr/vdr-plugin-skindesigner/dtd/displaychannel.dtd
<?xml encoding="UTF-8"?>

<!ENTITY % functions SYSTEM "functions.dtd">

<!ELEMENT displaychannel (background | channelinfo | epginfo | progressbar | progressbarback |  
                          statusinfo | audioinfo | ecminfo | screenresolution | channelgroup | 
                          signalquality | signalqualityback | devices | currentweather | scrapercontent |  
                          datetime | time | message | customtokens)* >
<!ATTLIST displaychannel
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #REQUIRED
  height CDATA #REQUIRED
  fadetime CDATA #IMPLIED
  shifttime CDATA #IMPLIED
  shifttype CDATA #IMPLIED
  shiftmode CDATA #IMPLIED
  startx CDATA #IMPLIED
  starty CDATA #IMPLIED
  scaletvx CDATA #IMPLIED
  scaletvy CDATA #IMPLIED
  scaletvwidth CDATA #IMPLIED
  scaletvheight CDATA #IMPLIED
  debuggrid CDATA #IMPLIED
>

<!ELEMENT background (areacontainer|area|areascroll)*>
<!ATTLIST background
  debug CDATA #IMPLIED
  condition CDATA #IMPLIED
>

<!ELEMENT channelinfo (areacontainer|area|areascroll)*>
<!ATTLIST channelinfo
  debug CDATA #IMPLIED
  condition CDATA #IMPLIED
>

<!ELEMENT epginfo (areacontainer|area|areascroll)*>
<!ATTLIST epginfo
  debug CDATA #IMPLIED
  condition CDATA #IMPLIED
>

<!ELEMENT progressbar (areacontainer|area|areascroll)*>
<!ATTLIST progressbar
  debug CDATA #IMPLIED
  condition CDATA #IMPLIED
>

<!ELEMENT progressbarback (areacontainer|area|areascroll)*>
<!ATTLIST progressbarback
  debug CDATA #IMPLIED
  condition CDATA #IMPLIED
>

<!ELEMENT statusinfo (areacontainer|area|areascroll)*>
<!ATTLIST statusinfo
  debug CDATA #IMPLIED
  condition CDATA #IMPLIED
>

<!ELEMENT audioinfo (areacontainer|area|areascroll)*>
<!ATTLIST audioinfo
  debug CDATA #IMPLIED
  condition CDATA #IMPLIED
>

<!ELEMENT ecminfo (areacontainer|area|areascroll)*>
<!ATTLIST ecminfo
  debug CDATA #IMPLIED
  condition CDATA #IMPLIED
>

<!ELEMENT screenresolution (areacontainer|area|areascroll)*>
<!ATTLIST screenresolution
  debug CDATA #IMPLIED
  condition CDATA #IMPLIED
>

<!ELEMENT channelgroup (areacontainer|area|areascroll)*>
<!ATTLIST channelgroup
  debug CDATA #IMPLIED
  condition CDATA #IMPLIED
>

<!ELEMENT signalquality (areacontainer|area|areascroll)*>
<!ATTLIST signalquality
  debug CDATA #IMPLIED
  condition CDATA #IMPLIED
>

<!ELEMENT signalqualityback (areacontainer|area|areascroll)*>
<!ATTLIST signalqualityback
  debug CDATA #IMPLIED
  condition CDATA #IMPLIED
>

<!ELEMENT devices (areacontainer|area|areascroll)*>
<!ATTLIST devices
  detached CDATA #IMPLIED
  delay CDATA #IMPLIED
  fadetime CDATA #IMPLIED
  shifttime CDATA #IMPLIED
  shifttype CDATA #IMPLIED
  shiftmode CDATA #IMPLIED
  startx CDATA #IMPLIED
  starty CDATA #IMPLIED
  debug CDATA #IMPLIED
  condition CDATA #IMPLIED
  mode CDATA #IMPLIED
>

<!ELEMENT currentweather (areacontainer|area|areascroll)*>
<!ATTLIST currentweather
  detached CDATA #IMPLIED
  delay CDATA #IMPLIED
  fadetime CDATA #IMPLIED
  shifttime CDATA #IMPLIED
  shifttype CDATA #IMPLIED
  shiftmode CDATA #IMPLIED
  startx CDATA #IMPLIED
  starty CDATA #IMPLIED
  debug CDATA #IMPLIED
  condition CDATA #IMPLIED
>

<!ELEMENT scrapercontent (areacontainer|area|areascroll)*>
<!ATTLIST scrapercontent
  detached CDATA #IMPLIED
  delay CDATA #IMPLIED
  fadetime CDATA #IMPLIED
  shifttime CDATA #IMPLIED
  shifttype CDATA #IMPLIED
  shiftmode CDATA #IMPLIED
  startx CDATA #IMPLIED
  starty CDATA #IMPLIED
  debug CDATA #IMPLIED
  condition CDATA #IMPLIED
>

<!ELEMENT datetime (areacontainer|area|areascroll)*>
<!ATTLIST datetime
  detached CDATA #IMPLIED
  delay CDATA #IMPLIED
  fadetime CDATA #IMPLIED
  shifttime CDATA #IMPLIED
  shifttype CDATA #IMPLIED
  shiftmode CDATA #IMPLIED
  startx CDATA #IMPLIED
  starty CDATA #IMPLIED
  debug CDATA #IMPLIED
  condition CDATA #IMPLIED
>

<!ELEMENT time (areacontainer|area|areascroll)*>
<!ATTLIST time
  detached CDATA #IMPLIED
  delay CDATA #IMPLIED
  fadetime CDATA #IMPLIED
  shifttime CDATA #IMPLIED
  shifttype CDATA #IMPLIED
  shiftmode CDATA #IMPLIED
  startx CDATA #IMPLIED
  starty CDATA #IMPLIED
  debug CDATA #IMPLIED
  condition CDATA #IMPLIED
>

<!ELEMENT message (areacontainer|area|areascroll)*>
<!ATTLIST message
  debug CDATA #IMPLIED
  condition CDATA #IMPLIED
>

<!ELEMENT customtokens (areacontainer|area|areascroll)*>
<!ATTLIST customtokens
  detached CDATA #IMPLIED
  delay CDATA #IMPLIED
  fadetime CDATA #IMPLIED
  shifttime CDATA #IMPLIED
  shiftmode CDATA #IMPLIED
  startx CDATA #IMPLIED
  starty CDATA #IMPLIED
  debug CDATA #IMPLIED
  condition CDATA #IMPLIED
>

%functions;

=== yavdr/vdr-plugin-skindesigner/skinskeleton/xmlfiles/displaychannel.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE displaychannel SYSTEM "../../../dtd/displaychannel.dtd">

<displaychannel x="0" y="0" width="100%" height="100%" fadetime="0">

    <background>
    </background>

    <!-- Available Variables channelinfo:
    {channelnumber}                 Number of Channel, with "-" in case of channel switching
    {channelname}                   Name of current Channel
    {channellogoexists}             true if a channel logo exists 
    {channelid}                     ChannelID as path to display channel logo
    {switching}                     true if a number is pressed on the remote to switch to a dedicated channel
    -->
    <channelinfo>
    </channelinfo>

    <!-- Available Variables epginfo:
    {currenttitle}                     Title of the current Schedule
    {currentsubtitle}                  Subtitle of the current Schedule
    {currentstart}                     Start of current Schedule in hh:mm
    {currentstop}                      End of current Schedule in hh:mm 
    {currentduration}                  Duration of current Schedule in min
    {currentdurationhours}             Duration, full hours
    {currentdurationminutes}           Duration, rest of minutes
    {currentelapsed}                   Elapsed time of current Schedule in min
    {currentremaining}                 Remaining time of current Schedule in min
    {currentrecording}                 true if current Schedule is recorded
    {hasVPS}                           true if current Schedule has VPS
    {nexttitle}                        Title of next Schedule
    {nextsubtitle}                     Subtitle of next Schedule
    {nextstart}                        Start of next Schedule in hh:mm
    {nextstop}                         Stop of next Schedule in hh:mm
    {nextduration}                     Duration of next Schedule in min
    {nextdurationhours}                Duration, full hours
    {nextdurationminutes}              Duration, rest of minutes
    {nextrecording}                    true if next Schedule will be recorded
    -->
    <epginfo>
    </epginfo>

    <!-- Available Variables progressbar:
    {start}                            Start of current Schedule in hh:mm
    {stop}                             End of current Schedule in hh:mm 
    {duration}                         Total Duration of current Schedule in seconds
    {elapsed}                          Elapsed time of current Schedule in seconds
    {remaining}                        Remaining time of current Schedule in seconds
    {permashift}                       true if permashift plugin is in use
    {livebuffer}                       current buffered data in seconds
    -->
    <progressbar>
    </progressbar>

    <!-- Available Variables statusinfo:
    {isRadio}                          true if channel is a radio channel
    {hasVT}                            true if channel has video text   
    {isStereo}                         true if a stereo audio trac is available
    {isDolby}                          true if a dolby audio track is available
    {isEncrypted}                      true if channel is encrypted
    {isRecording}                      true if currently a recording is running on this channel
    {newmails}                         true if mailbox plugin is installed and new mails are available
    -->
    <statusinfo>
    </statusinfo>

    <!-- Available Variables audioinfo:
    {numaudiotracks}                   number of available audio tracks for current channel
    {audiochannel}                     0 if current channel is stereo, 1 for left chanel only, 2 for right channel only
    {trackdesc}                        description of the current audio track
    {tracklang}                        language of the current audio track
    -->
    <audioinfo>
    </audioinfo>

    <!-- Available Variables ecminfo:
    {caid}                              id of currently used CA
    {cardsystem}                        name of currently used CA
    {pid}                               pID
    {prid}                              provider ID
    {ecmtime}                           ecm time in ms
    {hops}                              number of hops
    {reader}                            name of used reader
    {from}                              name of originating host
    {protocol}                          used protocol of reader
    -->
    <ecminfo>
    </ecminfo>

    <!-- Available Variables screenresolution:
    {screenwidth}                      width of currently displayed channel in px
    {screenheight}                     height of currently displayed channel in px
    {resolution}                       resolution: hd1080i, hd720p, sd576i
    {aspect}                           screen aspect, each 4:3, 16:9 or 21:9
    {isHD}                             true for hd1080i and hd720p
    {isWideScreen}                     true if aspect is 16:9 or 21:9
    -->
    <screenresolution>
    </screenresolution>

    <!-- Available Variables dvbdeviceinfo:
    {prevAvailable}                     true if previous Channel Group is avaialble
    {nextAvailable}                     true if next Channel Group is avaialble
    {group}                             Name of current Channel Group
    {nextgroup}                         Name of next Channel Group
    {prevgroup}                         Name of prev Channel Group
    {sepexists}                         true if a channel separator logo exists
    {seppath}                           path for separator logo to use in imagetype "seplogo"
    -->
    <channelgroup>
    </channelgroup>

    <!-- Available Variables signalquality:
    {signalstrength}                    STR value of currently displayed channel
    {signalquality}                     SNR value of currently displayed channel
    -->
    <signalquality>
    </signalquality>

    <!-- background of signalmeter, will only be drawn if signalquality was deleted -->
    <signalqualityback>
    </signalqualityback>

    <!-- Available Variables devices:
    signalstrength and -quality are only set if not mode="light" is used in <devices>
    {numdevices}                number of available devices
    {devices[]}                 array with available devices
    {devices[num]}              number of current device
    {devices[type]}             type of device (DVB-S, DVB-C, ...)
    {devices[istuned]}          true if device is currently tuned to a transponder
    {devices[livetv]}           true if device is currently playing livetv
    {devices[recording]}        true if device is currently recording
    {devices[hascam]}           true if device has a CAM
    {devices[cam]}              number of CAM
    {devices[signalstrength]}   signalstrength of devcie
    {devices[signalquality]}    signalstrength of devcie
    {devices[channelnumber]}    number of the currently tuned channel
    {devices[channelname]}      name of the currently tuned channel
    {devices[channellogoexists]} true if a channel logo exists 
    {devices[channelid]}        ID of the currently tuned channel
    {devices[source]}           source of the currently tuned channel
    -->
    <devices mode="full|light">
    </devices>

    <!-- Available Variables currentweather:
    {timestamp}                 timestamp of forecast in dd.mm hh:mm
    {temperature}               current temperature in 째C
    {apparenttemperature}       apparent (feeled) temperature
    {mintemperature}            minimum daily temperature in 째C
    {maxtemperature}            maximum daily temperature in 째C
    {summary}                   short weather summary
    {icon}                      weather icon 
    {precipitationintensity}    precipitation intensity in l/m2
    {precipitationprobability}  precipitation probability in %
    {precipitationtype}         precipitation type
    {humidity}                  humidity in %
    {windspeed}                 windspeed in km/h
    {windbearing}               wind bearing in 째
    {windbearingstring}         wind bearing (N, NE, ...)
    {visibility}                visibility in km
    {cloudcover}                cloud cover in %
    {pressure}                  pressure in HPo
    {ozone}                     ozone value in DU
    -->
    <currentweather>
    </currentweather>

    <!-- Available Variables scrapercontent:
    {posterpath}                        Full Path of Poster to use in image path attribute
    {posterwidth}                       width of poster in pixel
    {posterheight}                      height of poster in pixel
    {hasPoster}                         true if poster is available
    {bannerpath}                        Full Path of banner to use in image path attribute
    {bannerwidth}                       width of banner in pixel
    {bannerheight}                      height of banner in pixel
    {hasBanner}                         true if banner is available

    Use this tokens if you want to display a banner for series and a poster for movies:
    {mediapath}                         Full Path of Poster or Banner to use in image path attribute
    {mediawidth}                        width of image in pixel
    {mediaheight}                       height of image in pixel
    {isbanner}                          true if image is a banner, false if it is a poster
    -->
    <scrapercontent>
    </scrapercontent>

    <!-- Available Variables datetime:
    {time}                              time in hh:mm
    {day}                               day in digits
    {dayleadingzero}                    day in digits with leading 0
    {dayname}                           Full name of the day
    {daynameshort}                      Short 3 char name of the day
    {month}                             month in digits with leading 0
    {monthname}                         Full name of the month
    {monthnameshort}                    3 letter abbrivation of month name
