=== yavdr/vdr-plugin-skindesigner/dtd/displayreplay.dtd
<?xml encoding="UTF-8"?>

<!ENTITY % functions SYSTEM "functions.dtd">

<!ELEMENT displayreplay (background | backgroundmodeonly |datetime | time | 
                         scrapercontent | rectitle | recinfo | currenttime | 
                         totaltime | endtime | progressbar | cutmarks | controlicons | 
                         controliconsmodeonly | jump | message | onpause | 
                         onpausemodeonly | customtokens)*>
<!ATTLIST displayreplay
  x CDATA #REQUIRED
  y CDATA #REQUIRED
  width CDATA #REQUIRED
  height CDATA #REQUIRED
  fadetime CDATA #IMPLIED
  shifttime CDATA #IMPLIED
  shifttype CDATA #IMPLIED
  shiftmode CDATA #IMPLIED
  startx CDATA #IMPLIED
  starty CDATA #IMPLIED
  scaletvx CDATA #IMPLIED
  scaletvy CDATA #IMPLIED
  scaletvwidth CDATA #IMPLIED
  scaletvheight CDATA #IMPLIED
  debuggrid CDATA #IMPLIED
>

<!ELEMENT background (area)*>
<!ATTLIST background
  debug CDATA #IMPLIED
>

<!ELEMENT backgroundmodeonly (area)*>
<!ATTLIST backgroundmodeonly
  debug CDATA #IMPLIED
>

<!ELEMENT datetime (area|areascroll)*>
<!ATTLIST datetime
  debug CDATA #IMPLIED
  condition CDATA #IMPLIED
>

<!ELEMENT time (area|areascroll)*>
<!ATTLIST time
  debug CDATA #IMPLIED
  condition CDATA #IMPLIED
>

<!ELEMENT scrapercontent (area|areascroll)*>
<!ATTLIST scrapercontent
  detached CDATA #IMPLIED
  delay CDATA #IMPLIED
  fadetime CDATA #IMPLIED
  shifttime CDATA #IMPLIED
  shifttype CDATA #IMPLIED
  shiftmode CDATA #IMPLIED
  startx CDATA #IMPLIED
  starty CDATA #IMPLIED
  debug CDATA #IMPLIED
  condition CDATA #IMPLIED
>

<!ELEMENT rectitle (area|areascroll)*>
<!ATTLIST rectitle
  debug CDATA #IMPLIED
  condition CDATA #IMPLIED
>

<!ELEMENT recinfo (area|areascroll)*>
<!ATTLIST recinfo
  debug CDATA #IMPLIED
  condition CDATA #IMPLIED
>

<!ELEMENT currenttime (area|areascroll)*>
<!ATTLIST currenttime
  debug CDATA #IMPLIED
  condition CDATA #IMPLIED
>

<!ELEMENT totaltime (area|areascroll)*>
<!ATTLIST totaltime
  debug CDATA #IMPLIED
  condition CDATA #IMPLIED
>

<!ELEMENT endtime (area|areascroll)*>
<!ATTLIST endtime
  debug CDATA #IMPLIED
  condition CDATA #IMPLIED
>

<!ELEMENT progressbar (area|areascroll)*>
<!ATTLIST progressbar
  debug CDATA #IMPLIED
  condition CDATA #IMPLIED
>

<!ELEMENT cutmarks (area|areascroll)*>
<!ATTLIST cutmarks
  debug CDATA #IMPLIED
  condition CDATA #IMPLIED
>

<!ELEMENT controlicons (area|areascroll)*>
<!ATTLIST controlicons
  debug CDATA #IMPLIED
  condition CDATA #IMPLIED
>

<!ELEMENT controliconsmodeonly (area|areascroll)*>
<!ATTLIST controliconsmodeonly
  debug CDATA #IMPLIED
  condition CDATA #IMPLIED
>

<!ELEMENT jump (area|areascroll)*>
<!ATTLIST jump
  debug CDATA #IMPLIED
  condition CDATA #IMPLIED
>

<!ELEMENT message (area|areascroll)*>
<!ATTLIST message
  debug CDATA #IMPLIED
  condition CDATA #IMPLIED
>

<!ELEMENT onpause (area|areascroll)*>
<!ATTLIST onpause
  debug CDATA #IMPLIED
  delay CDATA #REQUIRED
  fadetime CDATA #IMPLIED
  condition CDATA #IMPLIED
>

<!ELEMENT onpausemodeonly (area|areascroll)*>
<!ATTLIST onpausemodeonly
  debug CDATA #IMPLIED
  delay CDATA #REQUIRED
  fadetime CDATA #IMPLIED
  condition CDATA #IMPLIED
>

<!ELEMENT customtokens (area|areascroll)*>
<!ATTLIST customtokens
  debug CDATA #IMPLIED
  condition CDATA #IMPLIED
>

%functions;

=== yavdr/vdr-plugin-skindesigner/skinskeleton/xmlfiles/displayreplay.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE displayreplay SYSTEM "../../../dtd/displayreplay.dtd">

<displayreplay x="0" y="0" width="100%" height="100%" fadetime="0">

    <background>
    </background>

    <backgroundmodeonly>
    </backgroundmodeonly>

    <!-- Available Variables datetime:
    {time}                              time in hh:mm
    {day}                               day in digits
    {dayleadingzero}                    day in digits with leading 0
    {dayname}                           Full name of the day
    {daynameshort}                      Short 3 char name of the day
    {month}                             month in digits with leading 0
    {monthname}                         Full name of the month
    {monthnameshort}                    3 letter abbrivation of month name
    {year}                              year in yyyy
    -->
    <datetime>
    </datetime>

    <!-- Available Variables scrapercontent:
    {posterpath}                        Full Path of Poster to use in image path attribute
    {posterwidth}                       width of poster in pixel
    {posterheight}                      height of poster in pixel
    {hasPoster}                         true if poster is available
    {bannerpath}                        Full Path of banner to use in image path attribute
    {bannerwidth}                       width of banner in pixel
    {bannerheight}                      height of banner in pixel
    {hasBanner}                         true if banner is available

    Use this tokens if you want to display a banner for series and a poster for movies:
    {mediapath}                         Full Path of Poster or Banner to use in image path attribute
    {mediawidth}                        width of image in pixel
    {mediaheight}                       height of image in pixel
    {isbanner}                          true if image is a banner, false if it is a poster
    -->
    <scrapercontent>
    </scrapercontent>

    <!-- Available Variables rectitle:
    {rectitle}                     Title of Recording
    {recsubtitle}                  Subtitle of the Recording
    {recdate}                      Date Recording in dd.mm.yy
    {rectime}                      Time of Recording in hh:mm
    -->
    <rectitle>
    </rectitle>

    <!-- Available Variables recinfo:
    {screenwidth}                      width of currently displayed recording in px
    {screenheight}                     height of currently displayed recording in px
    {resolution}                       resolution: hd1080i, hd720p, sd576i
    {aspect}                           screen aspect, each 4:3, 16:9 or 21:9
    {isHD}                             true for hd1080i and hd720p
    {isWideScreen}                     true if aspect is 16:9 or 21:9
    -->
    <recinfo>
    </recinfo>

    <!-- Available Variables currenttime:
    {reccurrent}                   Current Time in hh:mm:ss
    -->
    <currenttime>
    </currenttime>

    <!-- Available Variables totaltime:
    {rectotal}                   Total Time in hh:mm:ss
    {timeshift}                  true if a timeshifted recording is displayed
    {timeshifttotal}             Total Time of timeshift event in hh:mm
    -->
    <totaltime>
    </totaltime>

    <!-- Available Variables endtime:
    {recend}                     End Time in hh:mm
    -->
    <endtime>
    </endtime>

    <!-- Available Variables progressbar:
    {current}                   current frame of recording
    {total}                     total frames of recording
    {timeshift}                 true if a timeshifted recording is displayed
    {timeshifttotal}            total number of frames of timeshift event
    -->
    <progressbar>
    </progressbar>

    <!-- Available Variables cutmarks:
    {timeshift}                 true if a timeshifted recording is displayed
    {marks[]}                   array of available marks
    {marks[position]}           frame of current mark
    {marks[endposition]}        frame where startmark ends
    {marks[total]}              total number of frames
    {marks[timeshifttotal]}     total number of frames of timeshift event
    {marks[active]}             true if current replay position hits exactly the mark
    {marks[startmark]}          true if mark is start mark
    -->
    <cutmarks>
    </cutmarks>

    <!-- Available Variables controlicons and controliconsmodeonly:
    {play}              true if recording is played currently
    {pause}             true if recording is paused
    {forward}           true if fast forwarding 
    {forward1x}         true if fast forwarding 1x (with 3 trickspeeds)
    {forward2x}         true if fast forwarding 2x (with 3 trickspeeds)
    {forward3x}         true if fast forwarding 3x (with 3 trickspeeds)
    {rewind}            true if rewinding 
    {rewind1x}          true if rewinding 1x (with 3 trickspeeds)
    {rewind2x}          true if rewinding 2x (with 3 trickspeeds)
    {rewind3x}          true if rewinding 3x (with 3 trickspeeds)
    -->
    <controlicons>
    </controlicons>

    <controliconsmodeonly>
    </controliconsmodeonly>

    <!-- Available Variables jump:
    {jump}                      time to jump to in hh:mm
    -->
    <jump>
    </jump>
    <!-- Available Variables message:
    {text}                     message text
    {status}                   true if message is a status message
    {info}                     true if message is a info message
    {warning}                  true if message is a warn message
    {error}                    true if message is a error message
    -->
    <message>
    </message>

    <!-- Available Variables onpause and onpausemodeonly:
    {name}                    title of recording
    {shorttext}               shorttext of recording
    {description}             description of recording
    {date}                    date of recording in dd.mm.yy
    {time}                    time of recording in hh:mm
    {daynumeric}              day as number
    {month}                   month as number
    {year}                    year as number
    {duration}                real duration of recording in minutes
    {durationhours}           real duration, full hours
    {durationminutes}         real duration, rest of minutes
    {durationevent}           duration of corresponding event in minutes
    {durationeventhours}      event duration, full hours
    {durationeventminutes}    event duration, rest of minutes

    {ismovie}                 true if event is scraped as a movie
    Available variables for movies:
    {movietitle}              movie title from themoviedb
    {movieoriginalTitle}      movie original title from themoviedb
    {movietagline}            movie tagline from themoviedb
    {movieoverview}           movie overview from themoviedb
    {movieadult}              true if movie is rated as adult
    {moviebudget}             movie budget from themoviedb in $
    {movierevenue}            movie revenue from themoviedb in $
    {moviegenres}             movie genres from themoviedb
    {moviehomepage}           movie homepage from themoviedb
    {moviereleasedate}        movie release date from themoviedb
    {movieruntime}            movie runtime from themoviedb
    {moviepopularity}         movie popularity from themoviedb
    {movievoteaverage}        movie vote average from themoviedb
    {posterwidth}             width of scraped poster
    {posterheight}            height of scraped poster
    {posterpath}              absolute path of scraped poster
    {fanartwidth}             width of scraped fanart
    {fanartheight}            height of scraped fanart
    {fanartpath}              absolute path of scraped fanart
    {movieiscollection}       true if movie is part of a collection
    {moviecollectionName}     name of movie collection
    {collectionposterwidth}   width of scraped collection poster
    {collectionposterheight}  height of scraped collection poster
    {collectionposterpath}    absolute path of scraped collection poster
    {collectionfanartwidth}   width of scraped collection fanart
    {collectionfanartheight}  height of scraped collection fanart
    {collectionfanartpath}    absolute path of scraped collection fanart
    {actors[]}                array with movie actors
    {actors[name]}            real name of actor
    {actors[role]}            actor role
    {actors[thumb]}           absolute path of scraped actor thumb
    {actors[thumbwidth]}      width of scraped actor thumb
    {actors[thumbheight]}     height of scraped actor thumb

    {isseries}                true if event is scraped as a series
    Available variables for series:
    {seriesname}              name of series
    {seriesoverview}          series overview
    {seriesfirstaired}        first aired date 
    {seriesnetwork}           network which produces series
    {seriesgenre}             series genre
    {seriesrating}            series thetvdb rating
    {seriesstatus}            status of series (running / finished)
    {episodetitle}            title of episode
    {episodenumber}           number of episode
    {episodeseason}           season of episode
    {episodefirstaired}       first aired date of episode
    {episodegueststars}       guest stars of episode
    {episodeoverview}         episode overview
    {episoderating}           user rating for episode
    {episodeimagewidth}       episode image width
    {episodeimageheight}      episode image height
    {episodeimagepath}        episode image path
    {seasonposterwidth}       episode season poster width
    {seasonposterheight}      episode season poster height
    {seasonposterpath}        episode season poster path
    {seriesposter1width}      width of 1st poster
    {seriesposter1height}     height of 1st poster
    {seriesposter1path}       path of 1st poster
    {seriesposter2width}      width of 2nd poster
